/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diupractica1;

/**
 *
 * @author Entrar
 */
public class DIUPractica1 extends javax.swing.JFrame {

    /**
     * Creates new form DIUPractica1
     */
    public DIUPractica1() {
        initComponents();
        campoTextoMillas.setToolTipText("Introducir número entero o decimal.");
        campoTextoKilometros.setToolTipText("Introducir número entero o decimal.");
        campoTextoFactor.setToolTipText("Introducir número entero o decimal.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCalcular = new javax.swing.JButton();
        campoTextoMillas = new javax.swing.JTextField();
        millas = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        raulLozanoPonce = new javax.swing.JLabel();
        pabloPerdomoFalcon = new javax.swing.JLabel();
        millasKilometros = new javax.swing.JLabel();
        kilometrosMillas = new javax.swing.JLabel();
        kilometros = new javax.swing.JLabel();
        campoTextoKilometros = new javax.swing.JTextField();
        resultadoKilometros = new javax.swing.JLabel();
        resultadoMillas = new javax.swing.JLabel();
        factorDeConversion = new javax.swing.JLabel();
        campoTextoFactor = new javax.swing.JTextField();
        unaMilla = new javax.swing.JLabel();
        km = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        millas.setText("Millas:");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Conversor de Unidades");

        raulLozanoPonce.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        raulLozanoPonce.setText("Raúl Lozano Ponce");

        pabloPerdomoFalcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pabloPerdomoFalcon.setText("Pablo Perdomo Falcón");

        millasKilometros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        millasKilometros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        millasKilometros.setText("Millas - Kilómetros (Km)");

        kilometrosMillas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kilometrosMillas.setText("Kilómetros (Km) - Millas");

        kilometros.setText("Kilómetros (Km):");

        resultadoKilometros.setText(" ");
        resultadoKilometros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultadoMillas.setText(" ");
        resultadoMillas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        factorDeConversion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        factorDeConversion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factorDeConversion.setText("Factor de conversión");

        campoTextoFactor.setText("1.6");

        unaMilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unaMilla.setText("1 milla = ");

        km.setText("Km");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kilometrosMillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoMillas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoKilometros, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(millasKilometros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(factorDeConversion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoMillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(raulLozanoPonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pabloPerdomoFalcon, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(unaMilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(km)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(factorDeConversion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unaMilla)
                    .addComponent(km))
                .addGap(18, 18, 18)
                .addComponent(millasKilometros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(millas)
                    .addComponent(resultadoKilometros)
                    .addComponent(campoTextoMillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kilometrosMillas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilometros)
                    .addComponent(campoTextoKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoMillas))
                .addGap(18, 18, 18)
                .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raulLozanoPonce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pabloPerdomoFalcon)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        float factor = 0;
        try {
            factor = Float.parseFloat(campoTextoFactor.getText());
        } catch (NumberFormatException excepcion) {
            return;
        }
        if(!"".equals(campoTextoMillas.getText())){
            try {
                float millas = Float.parseFloat(campoTextoMillas.getText());
                resultadoKilometros.setText(" = " + (millas*factor) + " Km");
            } catch (NumberFormatException excepcion) {
                resultadoKilometros.setText(" ");
            }
        }
        if(!"".equals(campoTextoKilometros.getText())){
            try {
                float kilometros = Float.parseFloat(campoTextoKilometros.getText());
                resultadoMillas.setText(" = " + (kilometros/factor) + " Millas");
            } catch (NumberFormatException excepcion) {
                resultadoMillas.setText(" ");
            }
        }
    }//GEN-LAST:event_botonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIUPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIUPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIUPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIUPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIUPractica1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JTextField campoTextoFactor;
    private javax.swing.JTextField campoTextoKilometros;
    private javax.swing.JTextField campoTextoMillas;
    private javax.swing.JLabel factorDeConversion;
    private javax.swing.JLabel kilometros;
    private javax.swing.JLabel kilometrosMillas;
    private javax.swing.JLabel km;
    private javax.swing.JLabel millas;
    private javax.swing.JLabel millasKilometros;
    private javax.swing.JLabel pabloPerdomoFalcon;
    private javax.swing.JLabel raulLozanoPonce;
    private javax.swing.JLabel resultadoKilometros;
    private javax.swing.JLabel resultadoMillas;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel unaMilla;
    // End of variables declaration//GEN-END:variables
}
